// Auto-generated from Excel data
import 'package:latlong2/latlong.dart';

class PublicTransportRoute {
  final String id;
  final String nameAr;
  final String nameEn;
  final String fromAr;
  final String fromEn;
  final String toAr;
  final String toEn;
  final String zone;
  final String vehicleType;
  final double lengthKm;
  final int numStops;
  final int durationMinutes;
  final int frequencyMinutes;
  final double fareEgp;
  final String startTime;
  final String endTime;
  final bool isCng;
  final bool isAc;
  final bool isAccessible;

  const PublicTransportRoute({
    required this.id,
    required this.nameAr,
    required this.nameEn,
    required this.fromAr,
    required this.fromEn,
    required this.toAr,
    required this.toEn,
    required this.zone,
    required this.vehicleType,
    required this.lengthKm,
    required this.numStops,
    required this.durationMinutes,
    required this.frequencyMinutes,
    required this.fareEgp,
    required this.startTime,
    required this.endTime,
    required this.isCng,
    required this.isAc,
    required this.isAccessible,
  });
}

class PublicTransportData {
  static const List<PublicTransportRoute> routes = [
    PublicTransportRoute(
      id: '101',
      nameAr: 'المنيرة – شبرا الخيمة',
      nameEn: 'El-Munira – Shubra El-Kheima',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'شبرا الخيمة',
      toEn: 'Shubra El-Kheima',
      zone: 'وسط القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 8.9,
      numStops: 16,
      durationMinutes: 22,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '00:30',
      isCng: false,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '102',
      nameAr: 'الدقي – السيدة زينب',
      nameEn: 'Dokki – Sayeda Zeinab',
      fromAr: 'الدقي',
      fromEn: 'Dokki',
      toAr: 'السيدة زينب',
      toEn: 'Sayeda Zeinab',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 17.5,
      numStops: 8,
      durationMinutes: 55,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:15',
      endTime: '00:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '103',
      nameAr: 'كورنيش النيل – إمبابة',
      nameEn: 'Nile Corniche – Embaba',
      fromAr: 'كورنيش النيل',
      fromEn: 'Nile Corniche',
      toAr: 'إمبابة',
      toEn: 'Embaba',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 26.2,
      numStops: 20,
      durationMinutes: 60,
      frequencyMinutes: 15,
      fareEgp: 7,
      startTime: '05:00',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '104',
      nameAr: 'المنيرة – دار السلام',
      nameEn: 'El-Munira – Dar El-Salam',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'دار السلام',
      toEn: 'Dar El-Salam',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 13.5,
      numStops: 19,
      durationMinutes: 33,
      frequencyMinutes: 15,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '00:00',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '105',
      nameAr: 'القلعة – العباسية',
      nameEn: 'The Citadel – Abbasiya',
      fromAr: 'القلعة',
      fromEn: 'The Citadel',
      toAr: 'العباسية',
      toEn: 'Abbasiya',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 15.8,
      numStops: 9,
      durationMinutes: 51,
      frequencyMinutes: 18,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '106',
      nameAr: 'السيدة زينب – حلوان',
      nameEn: 'Sayeda Zeinab – Helwan',
      fromAr: 'السيدة زينب',
      fromEn: 'Sayeda Zeinab',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 20.3,
      numStops: 12,
      durationMinutes: 58,
      frequencyMinutes: 10,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '23:30',
      isCng: false,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '107',
      nameAr: 'جاردن سيتي – كورنيش النيل',
      nameEn: 'Garden City – Nile Corniche',
      fromAr: 'جاردن سيتي',
      fromEn: 'Garden City',
      toAr: 'كورنيش النيل',
      toEn: 'Nile Corniche',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 11.9,
      numStops: 25,
      durationMinutes: 37,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '108',
      nameAr: 'دار السلام – الجمالية',
      nameEn: 'Dar El-Salam – El-Gamaliya',
      fromAr: 'دار السلام',
      fromEn: 'Dar El-Salam',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 13.5,
      numStops: 32,
      durationMinutes: 45,
      frequencyMinutes: 10,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '109',
      nameAr: 'الأزبكية – الجمالية',
      nameEn: 'Azbakeya – El-Gamaliya',
      fromAr: 'الأزبكية',
      fromEn: 'Azbakeya',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 26.1,
      numStops: 12,
      durationMinutes: 61,
      frequencyMinutes: 18,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '00:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '110',
      nameAr: 'الهرم – الدقي',
      nameEn: 'El-Haram – Dokki',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'الدقي',
      toEn: 'Dokki',
      zone: 'جنوب غرب / غرب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 12.1,
      numStops: 15,
      durationMinutes: 27,
      frequencyMinutes: 10,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '111',
      nameAr: 'قصر النيل – بشتيل',
      nameEn: 'Qasr El-Nil – Bashteel',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'بشتيل',
      toEn: 'Bashteel',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 15.3,
      numStops: 12,
      durationMinutes: 48,
      frequencyMinutes: 20,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '22:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '112',
      nameAr: 'حلوان – كورنيش النيل',
      nameEn: 'Helwan – Nile Corniche',
      fromAr: 'حلوان',
      fromEn: 'Helwan',
      toAr: 'كورنيش النيل',
      toEn: 'Nile Corniche',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 19.5,
      numStops: 11,
      durationMinutes: 49,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '113',
      nameAr: 'الجمالية – عباس العقاد',
      nameEn: 'El-Gamaliya – Abbas El-Akkad',
      fromAr: 'الجمالية',
      fromEn: 'El-Gamaliya',
      toAr: 'عباس العقاد',
      toEn: 'Abbas El-Akkad',
      zone: 'وسط القاهرة / شرق القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 13.7,
      numStops: 23,
      durationMinutes: 38,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '114',
      nameAr: 'العباسية – السيدة زينب',
      nameEn: 'Abbasiya – Sayeda Zeinab',
      fromAr: 'العباسية',
      fromEn: 'Abbasiya',
      toAr: 'السيدة زينب',
      toEn: 'Sayeda Zeinab',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 33.0,
      numStops: 9,
      durationMinutes: 104,
      frequencyMinutes: 10,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '22:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '115',
      nameAr: 'مصر القديمة – باب الشعرية',
      nameEn: 'Old Cairo – Bab El-Shaeria',
      fromAr: 'مصر القديمة',
      fromEn: 'Old Cairo',
      toAr: 'باب الشعرية',
      toEn: 'Bab El-Shaeria',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 22.3,
      numStops: 26,
      durationMinutes: 65,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '116',
      nameAr: 'أكتوبر – النزهة',
      nameEn: 'October – El-Nozha',
      fromAr: 'أكتوبر',
      fromEn: 'October',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'غرب القاهرة / شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 25.2,
      numStops: 12,
      durationMinutes: 86,
      frequencyMinutes: 10,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '117',
      nameAr: 'شبرا الخيمة – شبرا',
      nameEn: 'Shubra El-Kheima – Shubra',
      fromAr: 'شبرا الخيمة',
      fromEn: 'Shubra El-Kheima',
      toAr: 'شبرا',
      toEn: 'Shubra',
      zone: 'شمال القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 33.2,
      numStops: 12,
      durationMinutes: 84,
      frequencyMinutes: 20,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '118',
      nameAr: 'المنيرة – المرج',
      nameEn: 'El-Munira – El-Marg',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'المرج',
      toEn: 'El-Marg',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 13.5,
      numStops: 22,
      durationMinutes: 39,
      frequencyMinutes: 18,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '119',
      nameAr: 'المعادي – النزهة',
      nameEn: 'Maadi – El-Nozha',
      fromAr: 'المعادي',
      fromEn: 'Maadi',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'جنوب القاهرة / شمال شرق',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 31.2,
      numStops: 29,
      durationMinutes: 72,
      frequencyMinutes: 30,
      fareEgp: 7,
      startTime: '05:00',
      endTime: '00:30',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '120',
      nameAr: 'قصر النيل – الدراسة',
      nameEn: 'Qasr El-Nil – El-Darasa',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'الدراسة',
      toEn: 'El-Darasa',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 35.6,
      numStops: 16,
      durationMinutes: 85,
      frequencyMinutes: 25,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '121',
      nameAr: 'المقطم – بدر',
      nameEn: 'El-Mokattam – Badr',
      fromAr: 'المقطم',
      fromEn: 'El-Mokattam',
      toAr: 'بدر',
      toEn: 'Badr',
      zone: 'جنوب شرق / شرق القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 37.4,
      numStops: 32,
      durationMinutes: 95,
      frequencyMinutes: 25,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:30',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '122',
      nameAr: 'كورنيش النيل – السلام',
      nameEn: 'Nile Corniche – El-Salam',
      fromAr: 'كورنيش النيل',
      fromEn: 'Nile Corniche',
      toAr: 'السلام',
      toEn: 'El-Salam',
      zone: 'وسط القاهرة / شرق القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 22.8,
      numStops: 24,
      durationMinutes: 53,
      frequencyMinutes: 20,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '22:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '123',
      nameAr: 'قصر النيل – شبرا الخيمة',
      nameEn: 'Qasr El-Nil – Shubra El-Kheima',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'شبرا الخيمة',
      toEn: 'Shubra El-Kheima',
      zone: 'وسط القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 32.5,
      numStops: 17,
      durationMinutes: 92,
      frequencyMinutes: 25,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '124',
      nameAr: 'عين شمس الشرقية – النزهة',
      nameEn: 'Ain Shams East – El-Nozha',
      fromAr: 'عين شمس الشرقية',
      fromEn: 'Ain Shams East',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 22.6,
      numStops: 26,
      durationMinutes: 67,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '125',
      nameAr: 'جاردن سيتي – المعصرة',
      nameEn: 'Garden City – El-Masara',
      fromAr: 'جاردن سيتي',
      fromEn: 'Garden City',
      toAr: 'المعصرة',
      toEn: 'El-Masara',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 15.6,
      numStops: 14,
      durationMinutes: 37,
      frequencyMinutes: 10,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '22:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '126',
      nameAr: 'الجمالية – القلعة',
      nameEn: 'El-Gamaliya – The Citadel',
      fromAr: 'الجمالية',
      fromEn: 'El-Gamaliya',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 38.1,
      numStops: 32,
      durationMinutes: 104,
      frequencyMinutes: 12,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '00:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '127',
      nameAr: 'مصر القديمة – كورنيش النيل',
      nameEn: 'Old Cairo – Nile Corniche',
      fromAr: 'مصر القديمة',
      fromEn: 'Old Cairo',
      toAr: 'كورنيش النيل',
      toEn: 'Nile Corniche',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 38.3,
      numStops: 21,
      durationMinutes: 125,
      frequencyMinutes: 20,
      fareEgp: 6,
      startTime: '05:15',
      endTime: '23:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '128',
      nameAr: 'عباس العقاد – بدر',
      nameEn: 'Abbas El-Akkad – Badr',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'بدر',
      toEn: 'Badr',
      zone: 'شرق القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 19.4,
      numStops: 25,
      durationMinutes: 44,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:15',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '129',
      nameAr: 'بولاق الدكرور – رمسيس',
      nameEn: 'Bulaq El-Dakrour – Ramses',
      fromAr: 'بولاق الدكرور',
      fromEn: 'Bulaq El-Dakrour',
      toAr: 'رمسيس',
      toEn: 'Ramses',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 40.1,
      numStops: 17,
      durationMinutes: 127,
      frequencyMinutes: 30,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '00:30',
      isCng: false,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '130',
      nameAr: 'إمبابة – روض الفرج',
      nameEn: 'Embaba – Rod El-Farag',
      fromAr: 'إمبابة',
      fromEn: 'Embaba',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'غرب القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 41.3,
      numStops: 25,
      durationMinutes: 92,
      frequencyMinutes: 18,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '22:30',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '131',
      nameAr: 'المقطم – الجمالية',
      nameEn: 'El-Mokattam – El-Gamaliya',
      fromAr: 'المقطم',
      fromEn: 'El-Mokattam',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'جنوب شرق / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 37.9,
      numStops: 16,
      durationMinutes: 120,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '132',
      nameAr: 'مصر القديمة – الزيتون',
      nameEn: 'Old Cairo – Zeitoun',
      fromAr: 'مصر القديمة',
      fromEn: 'Old Cairo',
      toAr: 'الزيتون',
      toEn: 'Zeitoun',
      zone: 'جنوب القاهرة / شمال شرق',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 16.1,
      numStops: 23,
      durationMinutes: 49,
      frequencyMinutes: 20,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '133',
      nameAr: 'زين العابدين – جاردن سيتي',
      nameEn: 'Zein El-Abedin – Garden City',
      fromAr: 'زين العابدين',
      fromEn: 'Zein El-Abedin',
      toAr: 'جاردن سيتي',
      toEn: 'Garden City',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 38.9,
      numStops: 20,
      durationMinutes: 105,
      frequencyMinutes: 25,
      fareEgp: 4,
      startTime: '05:15',
      endTime: '00:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '134',
      nameAr: 'الأزبكية – فيصل',
      nameEn: 'Azbakeya – Faisal',
      fromAr: 'الأزبكية',
      fromEn: 'Azbakeya',
      toAr: 'فيصل',
      toEn: 'Faisal',
      zone: 'وسط القاهرة / جنوب غرب',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 30.0,
      numStops: 8,
      durationMinutes: 99,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:15',
      endTime: '23:30',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '135',
      nameAr: 'عباس العقاد – باب الشعرية',
      nameEn: 'Abbas El-Akkad – Bab El-Shaeria',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'باب الشعرية',
      toEn: 'Bab El-Shaeria',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 17.5,
      numStops: 22,
      durationMinutes: 44,
      frequencyMinutes: 18,
      fareEgp: 5,
      startTime: '05:15',
      endTime: '23:30',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '136',
      nameAr: 'الهرم – مصر الجديدة',
      nameEn: 'El-Haram – Heliopolis',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'مصر الجديدة',
      toEn: 'Heliopolis',
      zone: 'جنوب غرب / شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 10.9,
      numStops: 31,
      durationMinutes: 29,
      frequencyMinutes: 20,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '00:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '137',
      nameAr: 'الأميرية – الهرم',
      nameEn: 'Amiriya – El-Haram',
      fromAr: 'الأميرية',
      fromEn: 'Amiriya',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'شرق القاهرة / جنوب غرب',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 19.7,
      numStops: 31,
      durationMinutes: 57,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '138',
      nameAr: 'كورنيش النيل – السيدة زينب',
      nameEn: 'Nile Corniche – Sayeda Zeinab',
      fromAr: 'كورنيش النيل',
      fromEn: 'Nile Corniche',
      toAr: 'السيدة زينب',
      toEn: 'Sayeda Zeinab',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 41.2,
      numStops: 24,
      durationMinutes: 122,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '139',
      nameAr: 'شبرا – رمسيس',
      nameEn: 'Shubra – Ramses',
      fromAr: 'شبرا',
      fromEn: 'Shubra',
      toAr: 'رمسيس',
      toEn: 'Ramses',
      zone: 'شمال القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 27.5,
      numStops: 23,
      durationMinutes: 77,
      frequencyMinutes: 15,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '00:30',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '140',
      nameAr: 'عباس العقاد – شبرا الخيمة',
      nameEn: 'Abbas El-Akkad – Shubra El-Kheima',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'شبرا الخيمة',
      toEn: 'Shubra El-Kheima',
      zone: 'شرق القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 27.0,
      numStops: 21,
      durationMinutes: 80,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '141',
      nameAr: 'المنيرة – النزهة',
      nameEn: 'El-Munira – El-Nozha',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 17.0,
      numStops: 10,
      durationMinutes: 40,
      frequencyMinutes: 12,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '142',
      nameAr: 'السيدة زينب – قصر النيل',
      nameEn: 'Sayeda Zeinab – Qasr El-Nil',
      fromAr: 'السيدة زينب',
      fromEn: 'Sayeda Zeinab',
      toAr: 'قصر النيل',
      toEn: 'Qasr El-Nil',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 35.3,
      numStops: 14,
      durationMinutes: 97,
      frequencyMinutes: 20,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '143',
      nameAr: 'بدر – فيصل',
      nameEn: 'Badr – Faisal',
      fromAr: 'بدر',
      fromEn: 'Badr',
      toAr: 'فيصل',
      toEn: 'Faisal',
      zone: 'شرق القاهرة / جنوب غرب',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 26.4,
      numStops: 22,
      durationMinutes: 60,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '22:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '144',
      nameAr: 'الهرم – عابدين',
      nameEn: 'El-Haram – Abdin',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'عابدين',
      toEn: 'Abdin',
      zone: 'جنوب غرب / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 23.0,
      numStops: 16,
      durationMinutes: 56,
      frequencyMinutes: 20,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '00:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '145',
      nameAr: 'قصر النيل – حلوان',
      nameEn: 'Qasr El-Nil – Helwan',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 35.7,
      numStops: 25,
      durationMinutes: 80,
      frequencyMinutes: 10,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '22:30',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '146',
      nameAr: 'المنيرة – الدقي',
      nameEn: 'El-Munira – Dokki',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'الدقي',
      toEn: 'Dokki',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 33.8,
      numStops: 14,
      durationMinutes: 86,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '22:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '147',
      nameAr: 'مدينة نصر – شبرا الخيمة',
      nameEn: 'Nasr City – Shubra El-Kheima',
      fromAr: 'مدينة نصر',
      fromEn: 'Nasr City',
      toAr: 'شبرا الخيمة',
      toEn: 'Shubra El-Kheima',
      zone: 'شرق القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 23.7,
      numStops: 11,
      durationMinutes: 72,
      frequencyMinutes: 12,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '22:00',
      isCng: true,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '148',
      nameAr: 'بدر – القلعة',
      nameEn: 'Badr – The Citadel',
      fromAr: 'بدر',
      fromEn: 'Badr',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 34.9,
      numStops: 21,
      durationMinutes: 92,
      frequencyMinutes: 30,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:30',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '149',
      nameAr: 'الأميرية – الجمالية',
      nameEn: 'Amiriya – El-Gamaliya',
      fromAr: 'الأميرية',
      fromEn: 'Amiriya',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 26.5,
      numStops: 22,
      durationMinutes: 90,
      frequencyMinutes: 30,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '00:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '150',
      nameAr: 'التحرير – روض الفرج',
      nameEn: 'Tahrir – Rod El-Farag',
      fromAr: 'التحرير',
      fromEn: 'Tahrir',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'وسط القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 25.1,
      numStops: 26,
      durationMinutes: 66,
      frequencyMinutes: 10,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '151',
      nameAr: 'عابدين – باب الشعرية',
      nameEn: 'Abdin – Bab El-Shaeria',
      fromAr: 'عابدين',
      fromEn: 'Abdin',
      toAr: 'باب الشعرية',
      toEn: 'Bab El-Shaeria',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 37.0,
      numStops: 29,
      durationMinutes: 122,
      frequencyMinutes: 18,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '22:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '152',
      nameAr: 'المطرية – الزمالك',
      nameEn: 'Matariya – Zamalek',
      fromAr: 'المطرية',
      fromEn: 'Matariya',
      toAr: 'الزمالك',
      toEn: 'Zamalek',
      zone: 'شمال شرق / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 18.2,
      numStops: 8,
      durationMinutes: 41,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '00:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '153',
      nameAr: 'بشتيل – السيدة زينب',
      nameEn: 'Bashteel – Sayeda Zeinab',
      fromAr: 'بشتيل',
      fromEn: 'Bashteel',
      toAr: 'السيدة زينب',
      toEn: 'Sayeda Zeinab',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 12.9,
      numStops: 22,
      durationMinutes: 39,
      frequencyMinutes: 18,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '154',
      nameAr: 'مصر الجديدة – البساتين',
      nameEn: 'Heliopolis – El-Basatin',
      fromAr: 'مصر الجديدة',
      fromEn: 'Heliopolis',
      toAr: 'البساتين',
      toEn: 'El-Basatin',
      zone: 'شمال شرق / جنوب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 37.0,
      numStops: 11,
      durationMinutes: 92,
      frequencyMinutes: 20,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '155',
      nameAr: 'المنيرة – مصر الجديدة',
      nameEn: 'El-Munira – Heliopolis',
      fromAr: 'المنيرة',
      fromEn: 'El-Munira',
      toAr: 'مصر الجديدة',
      toEn: 'Heliopolis',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 29.1,
      numStops: 29,
      durationMinutes: 92,
      frequencyMinutes: 30,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '156',
      nameAr: 'عين شمس – مصر الجديدة',
      nameEn: 'Ain Shams – Heliopolis',
      fromAr: 'عين شمس',
      fromEn: 'Ain Shams',
      toAr: 'مصر الجديدة',
      toEn: 'Heliopolis',
      zone: 'شمال شرق',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 12.5,
      numStops: 25,
      durationMinutes: 41,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:15',
      endTime: '22:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '157',
      nameAr: 'جاردن سيتي – حلوان',
      nameEn: 'Garden City – Helwan',
      fromAr: 'جاردن سيتي',
      fromEn: 'Garden City',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 40.9,
      numStops: 25,
      durationMinutes: 109,
      frequencyMinutes: 30,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '158',
      nameAr: 'العتبة – مصر القديمة',
      nameEn: 'Ataba – Old Cairo',
      fromAr: 'العتبة',
      fromEn: 'Ataba',
      toAr: 'مصر القديمة',
      toEn: 'Old Cairo',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 38.1,
      numStops: 25,
      durationMinutes: 100,
      frequencyMinutes: 20,
      fareEgp: 6,
      startTime: '05:15',
      endTime: '23:00',
      isCng: true,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '159',
      nameAr: 'عباس العقاد – أكتوبر',
      nameEn: 'Abbas El-Akkad – October',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'أكتوبر',
      toEn: 'October',
      zone: 'شرق القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 12.6,
      numStops: 22,
      durationMinutes: 33,
      frequencyMinutes: 25,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '160',
      nameAr: 'الدقي – عباس العقاد',
      nameEn: 'Dokki – Abbas El-Akkad',
      fromAr: 'الدقي',
      fromEn: 'Dokki',
      toAr: 'عباس العقاد',
      toEn: 'Abbas El-Akkad',
      zone: 'غرب القاهرة / شرق القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 37.1,
      numStops: 11,
      durationMinutes: 128,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '00:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '161',
      nameAr: 'المقطم – عباس العقاد',
      nameEn: 'El-Mokattam – Abbas El-Akkad',
      fromAr: 'المقطم',
      fromEn: 'El-Mokattam',
      toAr: 'عباس العقاد',
      toEn: 'Abbas El-Akkad',
      zone: 'جنوب شرق / شرق القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 41.6,
      numStops: 26,
      durationMinutes: 102,
      frequencyMinutes: 30,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '162',
      nameAr: 'العتبة – روض الفرج',
      nameEn: 'Ataba – Rod El-Farag',
      fromAr: 'العتبة',
      fromEn: 'Ataba',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'وسط القاهرة / شمال القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 8.5,
      numStops: 15,
      durationMinutes: 25,
      frequencyMinutes: 10,
      fareEgp: 6,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '163',
      nameAr: 'إمبابة – عابدين',
      nameEn: 'Embaba – Abdin',
      fromAr: 'إمبابة',
      fromEn: 'Embaba',
      toAr: 'عابدين',
      toEn: 'Abdin',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 40.8,
      numStops: 9,
      durationMinutes: 142,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '23:30',
      isCng: false,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '164',
      nameAr: 'الخليفة – الهرم',
      nameEn: 'El-Khalifa – El-Haram',
      fromAr: 'الخليفة',
      fromEn: 'El-Khalifa',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'وسط القاهرة / جنوب غرب',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 18.0,
      numStops: 24,
      durationMinutes: 53,
      frequencyMinutes: 10,
      fareEgp: 7,
      startTime: '05:15',
      endTime: '23:00',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '165',
      nameAr: 'المنيل – السلام',
      nameEn: 'El-Manial – El-Salam',
      fromAr: 'المنيل',
      fromEn: 'El-Manial',
      toAr: 'السلام',
      toEn: 'El-Salam',
      zone: 'وسط القاهرة / شرق القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 30.6,
      numStops: 19,
      durationMinutes: 105,
      frequencyMinutes: 25,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '22:30',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '166',
      nameAr: 'قصر النيل – الجمالية',
      nameEn: 'Qasr El-Nil – El-Gamaliya',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 22.4,
      numStops: 31,
      durationMinutes: 50,
      frequencyMinutes: 15,
      fareEgp: 7,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '167',
      nameAr: 'الأميرية – القلعة',
      nameEn: 'Amiriya – The Citadel',
      fromAr: 'الأميرية',
      fromEn: 'Amiriya',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 35.8,
      numStops: 27,
      durationMinutes: 110,
      frequencyMinutes: 20,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:30',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '168',
      nameAr: 'الزيتون – الدراسة',
      nameEn: 'Zeitoun – El-Darasa',
      fromAr: 'الزيتون',
      fromEn: 'Zeitoun',
      toAr: 'الدراسة',
      toEn: 'El-Darasa',
      zone: 'شمال شرق / وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 29.5,
      numStops: 8,
      durationMinutes: 68,
      frequencyMinutes: 20,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '169',
      nameAr: 'بدر – الدقي',
      nameEn: 'Badr – Dokki',
      fromAr: 'بدر',
      fromEn: 'Badr',
      toAr: 'الدقي',
      toEn: 'Dokki',
      zone: 'شرق القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 30.5,
      numStops: 23,
      durationMinutes: 91,
      frequencyMinutes: 18,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '22:30',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '170',
      nameAr: 'رمسيس – النزهة',
      nameEn: 'Ramses – El-Nozha',
      fromAr: 'رمسيس',
      fromEn: 'Ramses',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 18.2,
      numStops: 14,
      durationMinutes: 58,
      frequencyMinutes: 30,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '171',
      nameAr: 'العتبة – إمبابة',
      nameEn: 'Ataba – Embaba',
      fromAr: 'العتبة',
      fromEn: 'Ataba',
      toAr: 'إمبابة',
      toEn: 'Embaba',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 39.3,
      numStops: 18,
      durationMinutes: 115,
      frequencyMinutes: 20,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: true,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '172',
      nameAr: 'المنيل – السيدة زينب',
      nameEn: 'El-Manial – Sayeda Zeinab',
      fromAr: 'المنيل',
      fromEn: 'El-Manial',
      toAr: 'السيدة زينب',
      toEn: 'Sayeda Zeinab',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس عادي',
      lengthKm: 21.6,
      numStops: 10,
      durationMinutes: 58,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: true,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '173',
      nameAr: 'شبرا – الزيتون',
      nameEn: 'Shubra – Zeitoun',
      fromAr: 'شبرا',
      fromEn: 'Shubra',
      toAr: 'الزيتون',
      toEn: 'Zeitoun',
      zone: 'شمال القاهرة / شمال شرق',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 16.7,
      numStops: 13,
      durationMinutes: 49,
      frequencyMinutes: 30,
      fareEgp: 6,
      startTime: '05:00',
      endTime: '23:00',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: '174',
      nameAr: 'المعصرة – بدر',
      nameEn: 'El-Masara – Badr',
      fromAr: 'المعصرة',
      fromEn: 'El-Masara',
      toAr: 'بدر',
      toEn: 'Badr',
      zone: 'جنوب القاهرة / شرق القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 28.1,
      numStops: 19,
      durationMinutes: 80,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '00:00',
      isCng: true,
      isAc: false,
      isAccessible: true,
    ),
    PublicTransportRoute(
      id: '175',
      nameAr: 'زين العابدين – عابدين',
      nameEn: 'Zein El-Abedin – Abdin',
      fromAr: 'زين العابدين',
      fromEn: 'Zein El-Abedin',
      toAr: 'عابدين',
      toEn: 'Abdin',
      zone: 'وسط القاهرة',
      vehicleType: 'أتوبيس CNG',
      lengthKm: 14.4,
      numStops: 27,
      durationMinutes: 40,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:15',
      endTime: '23:30',
      isCng: true,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-001',
      nameAr: 'طره – القلعة',
      nameEn: 'Tura – The Citadel',
      fromAr: 'طره',
      fromEn: 'Tura',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 11.1,
      numStops: 6,
      durationMinutes: 40,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-002',
      nameAr: 'قصر النيل – الخليفة',
      nameEn: 'Qasr El-Nil – El-Khalifa',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'الخليفة',
      toEn: 'El-Khalifa',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 22.3,
      numStops: 15,
      durationMinutes: 58,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-003',
      nameAr: 'الأميرية – البساتين',
      nameEn: 'Amiriya – El-Basatin',
      fromAr: 'الأميرية',
      fromEn: 'Amiriya',
      toAr: 'البساتين',
      toEn: 'El-Basatin',
      zone: 'شرق القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 17.5,
      numStops: 15,
      durationMinutes: 65,
      frequencyMinutes: 15,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-004',
      nameAr: 'النزهة – المقطم',
      nameEn: 'El-Nozha – El-Mokattam',
      fromAr: 'النزهة',
      fromEn: 'El-Nozha',
      toAr: 'المقطم',
      toEn: 'El-Mokattam',
      zone: 'شمال شرق / جنوب شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 23.9,
      numStops: 20,
      durationMinutes: 66,
      frequencyMinutes: 7,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-005',
      nameAr: 'روض الفرج – الخليفة',
      nameEn: 'Rod El-Farag – El-Khalifa',
      fromAr: 'روض الفرج',
      fromEn: 'Rod El-Farag',
      toAr: 'الخليفة',
      toEn: 'El-Khalifa',
      zone: 'شمال القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 11.9,
      numStops: 10,
      durationMinutes: 32,
      frequencyMinutes: 15,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-006',
      nameAr: 'مصر القديمة – عين شمس الشرقية',
      nameEn: 'Old Cairo – Ain Shams East',
      fromAr: 'مصر القديمة',
      fromEn: 'Old Cairo',
      toAr: 'عين شمس الشرقية',
      toEn: 'Ain Shams East',
      zone: 'جنوب القاهرة / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 19.8,
      numStops: 19,
      durationMinutes: 56,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-007',
      nameAr: 'فيصل – الهرم',
      nameEn: 'Faisal – El-Haram',
      fromAr: 'فيصل',
      fromEn: 'Faisal',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'جنوب غرب',
      vehicleType: 'ميكروباص',
      lengthKm: 12.8,
      numStops: 10,
      durationMinutes: 47,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-008',
      nameAr: 'الهرم – شبرا الخيمة',
      nameEn: 'El-Haram – Shubra El-Kheima',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'شبرا الخيمة',
      toEn: 'Shubra El-Kheima',
      zone: 'جنوب غرب / شمال القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 10.0,
      numStops: 10,
      durationMinutes: 29,
      frequencyMinutes: 12,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-009',
      nameAr: 'طره – العباسية',
      nameEn: 'Tura – Abbasiya',
      fromAr: 'طره',
      fromEn: 'Tura',
      toAr: 'العباسية',
      toEn: 'Abbasiya',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.3,
      numStops: 16,
      durationMinutes: 35,
      frequencyMinutes: 5,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-010',
      nameAr: 'عين شمس الشرقية – بولاق الدكرور',
      nameEn: 'Ain Shams East – Bulaq El-Dakrour',
      fromAr: 'عين شمس الشرقية',
      fromEn: 'Ain Shams East',
      toAr: 'بولاق الدكرور',
      toEn: 'Bulaq El-Dakrour',
      zone: 'شمال شرق / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 18.6,
      numStops: 9,
      durationMinutes: 67,
      frequencyMinutes: 10,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-011',
      nameAr: 'القلعة – عين شمس الشرقية',
      nameEn: 'The Citadel – Ain Shams East',
      fromAr: 'القلعة',
      fromEn: 'The Citadel',
      toAr: 'عين شمس الشرقية',
      toEn: 'Ain Shams East',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 9.0,
      numStops: 8,
      durationMinutes: 23,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-012',
      nameAr: 'فيصل – زين العابدين',
      nameEn: 'Faisal – Zein El-Abedin',
      fromAr: 'فيصل',
      fromEn: 'Faisal',
      toAr: 'زين العابدين',
      toEn: 'Zein El-Abedin',
      zone: 'جنوب غرب / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 9.1,
      numStops: 9,
      durationMinutes: 26,
      frequencyMinutes: 5,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-013',
      nameAr: 'الهرم – أكتوبر',
      nameEn: 'El-Haram – October',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'أكتوبر',
      toEn: 'October',
      zone: 'جنوب غرب / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 14.7,
      numStops: 5,
      durationMinutes: 45,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-014',
      nameAr: 'عباس العقاد – كورنيش النيل',
      nameEn: 'Abbas El-Akkad – Nile Corniche',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'كورنيش النيل',
      toEn: 'Nile Corniche',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 17.8,
      numStops: 8,
      durationMinutes: 65,
      frequencyMinutes: 15,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-015',
      nameAr: 'إمبابة – الزمالك',
      nameEn: 'Embaba – Zamalek',
      fromAr: 'إمبابة',
      fromEn: 'Embaba',
      toAr: 'الزمالك',
      toEn: 'Zamalek',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 14.0,
      numStops: 10,
      durationMinutes: 52,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-016',
      nameAr: 'المعصرة – فيصل',
      nameEn: 'El-Masara – Faisal',
      fromAr: 'المعصرة',
      fromEn: 'El-Masara',
      toAr: 'فيصل',
      toEn: 'Faisal',
      zone: 'جنوب القاهرة / جنوب غرب',
      vehicleType: 'ميكروباص',
      lengthKm: 12.4,
      numStops: 20,
      durationMinutes: 35,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-017',
      nameAr: 'المنيل – حلوان',
      nameEn: 'El-Manial – Helwan',
      fromAr: 'المنيل',
      fromEn: 'El-Manial',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.6,
      numStops: 17,
      durationMinutes: 58,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-018',
      nameAr: 'المنيل – الخليفة',
      nameEn: 'El-Manial – El-Khalifa',
      fromAr: 'المنيل',
      fromEn: 'El-Manial',
      toAr: 'الخليفة',
      toEn: 'El-Khalifa',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 24.9,
      numStops: 10,
      durationMinutes: 82,
      frequencyMinutes: 8,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-019',
      nameAr: 'الدقي – التحرير',
      nameEn: 'Dokki – Tahrir',
      fromAr: 'الدقي',
      fromEn: 'Dokki',
      toAr: 'التحرير',
      toEn: 'Tahrir',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.3,
      numStops: 16,
      durationMinutes: 66,
      frequencyMinutes: 10,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-020',
      nameAr: 'الزيتون – الخليفة',
      nameEn: 'Zeitoun – El-Khalifa',
      fromAr: 'الزيتون',
      fromEn: 'Zeitoun',
      toAr: 'الخليفة',
      toEn: 'El-Khalifa',
      zone: 'شمال شرق / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 18.2,
      numStops: 19,
      durationMinutes: 46,
      frequencyMinutes: 5,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-021',
      nameAr: 'الدقي – دار السلام',
      nameEn: 'Dokki – Dar El-Salam',
      fromAr: 'الدقي',
      fromEn: 'Dokki',
      toAr: 'دار السلام',
      toEn: 'Dar El-Salam',
      zone: 'غرب القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 11.8,
      numStops: 7,
      durationMinutes: 39,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-022',
      nameAr: 'الهرم – البساتين',
      nameEn: 'El-Haram – El-Basatin',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'البساتين',
      toEn: 'El-Basatin',
      zone: 'جنوب غرب / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 23.2,
      numStops: 8,
      durationMinutes: 67,
      frequencyMinutes: 8,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-023',
      nameAr: 'الأزبكية – الدقي',
      nameEn: 'Azbakeya – Dokki',
      fromAr: 'الأزبكية',
      fromEn: 'Azbakeya',
      toAr: 'الدقي',
      toEn: 'Dokki',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 7.6,
      numStops: 19,
      durationMinutes: 30,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-024',
      nameAr: 'بولاق – الزمالك',
      nameEn: 'Bulaq – Zamalek',
      fromAr: 'بولاق',
      fromEn: 'Bulaq',
      toAr: 'الزمالك',
      toEn: 'Zamalek',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 17.4,
      numStops: 16,
      durationMinutes: 56,
      frequencyMinutes: 5,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-025',
      nameAr: 'الأميرية – روض الفرج',
      nameEn: 'Amiriya – Rod El-Farag',
      fromAr: 'الأميرية',
      fromEn: 'Amiriya',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'شرق القاهرة / شمال القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 16.9,
      numStops: 7,
      durationMinutes: 43,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-026',
      nameAr: 'السلام – عابدين',
      nameEn: 'El-Salam – Abdin',
      fromAr: 'السلام',
      fromEn: 'El-Salam',
      toAr: 'عابدين',
      toEn: 'Abdin',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 5.6,
      numStops: 19,
      durationMinutes: 19,
      frequencyMinutes: 8,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-027',
      nameAr: 'المطرية – السلام',
      nameEn: 'Matariya – El-Salam',
      fromAr: 'المطرية',
      fromEn: 'Matariya',
      toAr: 'السلام',
      toEn: 'El-Salam',
      zone: 'شمال شرق / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 23.6,
      numStops: 12,
      durationMinutes: 71,
      frequencyMinutes: 12,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-028',
      nameAr: 'أكتوبر – باب الشعرية',
      nameEn: 'October – Bab El-Shaeria',
      fromAr: 'أكتوبر',
      fromEn: 'October',
      toAr: 'باب الشعرية',
      toEn: 'Bab El-Shaeria',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 14.6,
      numStops: 10,
      durationMinutes: 49,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-029',
      nameAr: 'القلعة – زين العابدين',
      nameEn: 'The Citadel – Zein El-Abedin',
      fromAr: 'القلعة',
      fromEn: 'The Citadel',
      toAr: 'زين العابدين',
      toEn: 'Zein El-Abedin',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 9.6,
      numStops: 11,
      durationMinutes: 35,
      frequencyMinutes: 10,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-030',
      nameAr: 'عباس العقاد – جاردن سيتي',
      nameEn: 'Abbas El-Akkad – Garden City',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'جاردن سيتي',
      toEn: 'Garden City',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.5,
      numStops: 19,
      durationMinutes: 32,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-031',
      nameAr: 'بولاق – السلام',
      nameEn: 'Bulaq – El-Salam',
      fromAr: 'بولاق',
      fromEn: 'Bulaq',
      toAr: 'السلام',
      toEn: 'El-Salam',
      zone: 'وسط القاهرة / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.4,
      numStops: 16,
      durationMinutes: 76,
      frequencyMinutes: 7,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-032',
      nameAr: 'الزيتون – شبرا',
      nameEn: 'Zeitoun – Shubra',
      fromAr: 'الزيتون',
      fromEn: 'Zeitoun',
      toAr: 'شبرا',
      toEn: 'Shubra',
      zone: 'شمال شرق / شمال القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 5.1,
      numStops: 17,
      durationMinutes: 19,
      frequencyMinutes: 10,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-033',
      nameAr: 'فيصل – إمبابة',
      nameEn: 'Faisal – Embaba',
      fromAr: 'فيصل',
      fromEn: 'Faisal',
      toAr: 'إمبابة',
      toEn: 'Embaba',
      zone: 'جنوب غرب / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 14.5,
      numStops: 14,
      durationMinutes: 47,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-034',
      nameAr: 'بشتيل – الخليفة',
      nameEn: 'Bashteel – El-Khalifa',
      fromAr: 'بشتيل',
      fromEn: 'Bashteel',
      toAr: 'الخليفة',
      toEn: 'El-Khalifa',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 22.5,
      numStops: 20,
      durationMinutes: 65,
      frequencyMinutes: 5,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-035',
      nameAr: 'العباسية – زين العابدين',
      nameEn: 'Abbasiya – Zein El-Abedin',
      fromAr: 'العباسية',
      fromEn: 'Abbasiya',
      toAr: 'زين العابدين',
      toEn: 'Zein El-Abedin',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 15.8,
      numStops: 16,
      durationMinutes: 52,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-036',
      nameAr: 'دار السلام – المقطم',
      nameEn: 'Dar El-Salam – El-Mokattam',
      fromAr: 'دار السلام',
      fromEn: 'Dar El-Salam',
      toAr: 'المقطم',
      toEn: 'El-Mokattam',
      zone: 'جنوب القاهرة / جنوب شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 15.7,
      numStops: 16,
      durationMinutes: 57,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-037',
      nameAr: 'الهرم – إمبابة',
      nameEn: 'El-Haram – Embaba',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'إمبابة',
      toEn: 'Embaba',
      zone: 'جنوب غرب / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 7.1,
      numStops: 9,
      durationMinutes: 21,
      frequencyMinutes: 12,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-038',
      nameAr: 'فيصل – أكتوبر',
      nameEn: 'Faisal – October',
      fromAr: 'فيصل',
      fromEn: 'Faisal',
      toAr: 'أكتوبر',
      toEn: 'October',
      zone: 'جنوب غرب / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 14.3,
      numStops: 14,
      durationMinutes: 45,
      frequencyMinutes: 5,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-039',
      nameAr: 'عابدين – القلعة',
      nameEn: 'Abdin – The Citadel',
      fromAr: 'عابدين',
      fromEn: 'Abdin',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 16.1,
      numStops: 12,
      durationMinutes: 57,
      frequencyMinutes: 12,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-040',
      nameAr: 'العتبة – الدقي',
      nameEn: 'Ataba – Dokki',
      fromAr: 'العتبة',
      fromEn: 'Ataba',
      toAr: 'الدقي',
      toEn: 'Dokki',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 10.6,
      numStops: 9,
      durationMinutes: 33,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-041',
      nameAr: 'بولاق الدكرور – الهرم',
      nameEn: 'Bulaq El-Dakrour – El-Haram',
      fromAr: 'بولاق الدكرور',
      fromEn: 'Bulaq El-Dakrour',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'غرب القاهرة / جنوب غرب',
      vehicleType: 'ميكروباص',
      lengthKm: 11.9,
      numStops: 10,
      durationMinutes: 37,
      frequencyMinutes: 12,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-042',
      nameAr: 'المعصرة – مدينة نصر',
      nameEn: 'El-Masara – Nasr City',
      fromAr: 'المعصرة',
      fromEn: 'El-Masara',
      toAr: 'مدينة نصر',
      toEn: 'Nasr City',
      zone: 'جنوب القاهرة / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 23.8,
      numStops: 14,
      durationMinutes: 87,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-043',
      nameAr: 'جاردن سيتي – أكتوبر',
      nameEn: 'Garden City – October',
      fromAr: 'جاردن سيتي',
      fromEn: 'Garden City',
      toAr: 'أكتوبر',
      toEn: 'October',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.0,
      numStops: 17,
      durationMinutes: 44,
      frequencyMinutes: 7,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-044',
      nameAr: 'بولاق الدكرور – النزهة',
      nameEn: 'Bulaq El-Dakrour – El-Nozha',
      fromAr: 'بولاق الدكرور',
      fromEn: 'Bulaq El-Dakrour',
      toAr: 'النزهة',
      toEn: 'El-Nozha',
      zone: 'غرب القاهرة / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 8.2,
      numStops: 13,
      durationMinutes: 31,
      frequencyMinutes: 15,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-045',
      nameAr: 'الهرم – مدينة نصر',
      nameEn: 'El-Haram – Nasr City',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'مدينة نصر',
      toEn: 'Nasr City',
      zone: 'جنوب غرب / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 17.4,
      numStops: 6,
      durationMinutes: 46,
      frequencyMinutes: 8,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-046',
      nameAr: 'عابدين – مصر الجديدة',
      nameEn: 'Abdin – Heliopolis',
      fromAr: 'عابدين',
      fromEn: 'Abdin',
      toAr: 'مصر الجديدة',
      toEn: 'Heliopolis',
      zone: 'وسط القاهرة / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 19.9,
      numStops: 14,
      durationMinutes: 59,
      frequencyMinutes: 15,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-047',
      nameAr: 'التحرير – حلوان',
      nameEn: 'Tahrir – Helwan',
      fromAr: 'التحرير',
      fromEn: 'Tahrir',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 20.5,
      numStops: 10,
      durationMinutes: 80,
      frequencyMinutes: 8,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-048',
      nameAr: 'بشتيل – روض الفرج',
      nameEn: 'Bashteel – Rod El-Farag',
      fromAr: 'بشتيل',
      fromEn: 'Bashteel',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'غرب القاهرة / شمال القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 21.9,
      numStops: 19,
      durationMinutes: 63,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-049',
      nameAr: 'زين العابدين – جاردن سيتي',
      nameEn: 'Zein El-Abedin – Garden City',
      fromAr: 'زين العابدين',
      fromEn: 'Zein El-Abedin',
      toAr: 'جاردن سيتي',
      toEn: 'Garden City',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.9,
      numStops: 10,
      durationMinutes: 67,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-050',
      nameAr: 'روض الفرج – بولاق الدكرور',
      nameEn: 'Rod El-Farag – Bulaq El-Dakrour',
      fromAr: 'روض الفرج',
      fromEn: 'Rod El-Farag',
      toAr: 'بولاق الدكرور',
      toEn: 'Bulaq El-Dakrour',
      zone: 'شمال القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 10.8,
      numStops: 12,
      durationMinutes: 27,
      frequencyMinutes: 10,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-051',
      nameAr: 'عباس العقاد – العباسية',
      nameEn: 'Abbas El-Akkad – Abbasiya',
      fromAr: 'عباس العقاد',
      fromEn: 'Abbas El-Akkad',
      toAr: 'العباسية',
      toEn: 'Abbasiya',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 18.0,
      numStops: 19,
      durationMinutes: 53,
      frequencyMinutes: 10,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-052',
      nameAr: 'الزيتون – إمبابة',
      nameEn: 'Zeitoun – Embaba',
      fromAr: 'الزيتون',
      fromEn: 'Zeitoun',
      toAr: 'إمبابة',
      toEn: 'Embaba',
      zone: 'شمال شرق / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.7,
      numStops: 16,
      durationMinutes: 61,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-053',
      nameAr: 'بولاق – دار السلام',
      nameEn: 'Bulaq – Dar El-Salam',
      fromAr: 'بولاق',
      fromEn: 'Bulaq',
      toAr: 'دار السلام',
      toEn: 'Dar El-Salam',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 5.6,
      numStops: 8,
      durationMinutes: 14,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-054',
      nameAr: 'السيدة زينب – بشتيل',
      nameEn: 'Sayeda Zeinab – Bashteel',
      fromAr: 'السيدة زينب',
      fromEn: 'Sayeda Zeinab',
      toAr: 'بشتيل',
      toEn: 'Bashteel',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 5.9,
      numStops: 19,
      durationMinutes: 21,
      frequencyMinutes: 10,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-055',
      nameAr: 'العتبة – حلوان',
      nameEn: 'Ataba – Helwan',
      fromAr: 'العتبة',
      fromEn: 'Ataba',
      toAr: 'حلوان',
      toEn: 'Helwan',
      zone: 'وسط القاهرة / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 9.3,
      numStops: 5,
      durationMinutes: 33,
      frequencyMinutes: 12,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-056',
      nameAr: 'عين شمس الشرقية – طره',
      nameEn: 'Ain Shams East – Tura',
      fromAr: 'عين شمس الشرقية',
      fromEn: 'Ain Shams East',
      toAr: 'طره',
      toEn: 'Tura',
      zone: 'شمال شرق / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 7.8,
      numStops: 9,
      durationMinutes: 28,
      frequencyMinutes: 15,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-057',
      nameAr: 'باب الشعرية – جاردن سيتي',
      nameEn: 'Bab El-Shaeria – Garden City',
      fromAr: 'باب الشعرية',
      fromEn: 'Bab El-Shaeria',
      toAr: 'جاردن سيتي',
      toEn: 'Garden City',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 24.2,
      numStops: 9,
      durationMinutes: 84,
      frequencyMinutes: 8,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-058',
      nameAr: 'إمبابة – جاردن سيتي',
      nameEn: 'Embaba – Garden City',
      fromAr: 'إمبابة',
      fromEn: 'Embaba',
      toAr: 'جاردن سيتي',
      toEn: 'Garden City',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 19.1,
      numStops: 18,
      durationMinutes: 62,
      frequencyMinutes: 7,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-059',
      nameAr: 'القلعة – العتبة',
      nameEn: 'The Citadel – Ataba',
      fromAr: 'القلعة',
      fromEn: 'The Citadel',
      toAr: 'العتبة',
      toEn: 'Ataba',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 9.1,
      numStops: 7,
      durationMinutes: 24,
      frequencyMinutes: 5,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-060',
      nameAr: 'النزهة – الجمالية',
      nameEn: 'El-Nozha – El-Gamaliya',
      fromAr: 'النزهة',
      fromEn: 'El-Nozha',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'شمال شرق / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 22.1,
      numStops: 6,
      durationMinutes: 59,
      frequencyMinutes: 8,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-061',
      nameAr: 'قصر النيل – الهرم',
      nameEn: 'Qasr El-Nil – El-Haram',
      fromAr: 'قصر النيل',
      fromEn: 'Qasr El-Nil',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'وسط القاهرة / جنوب غرب',
      vehicleType: 'ميكروباص',
      lengthKm: 8.6,
      numStops: 14,
      durationMinutes: 25,
      frequencyMinutes: 12,
      fareEgp: 3,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-062',
      nameAr: 'السلام – الزمالك',
      nameEn: 'El-Salam – Zamalek',
      fromAr: 'السلام',
      fromEn: 'El-Salam',
      toAr: 'الزمالك',
      toEn: 'Zamalek',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.7,
      numStops: 9,
      durationMinutes: 37,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-063',
      nameAr: 'العباسية – الأميرية',
      nameEn: 'Abbasiya – Amiriya',
      fromAr: 'العباسية',
      fromEn: 'Abbasiya',
      toAr: 'الأميرية',
      toEn: 'Amiriya',
      zone: 'وسط القاهرة / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.7,
      numStops: 18,
      durationMinutes: 42,
      frequencyMinutes: 7,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-064',
      nameAr: 'أكتوبر – كورنيش النيل',
      nameEn: 'October – Nile Corniche',
      fromAr: 'أكتوبر',
      fromEn: 'October',
      toAr: 'كورنيش النيل',
      toEn: 'Nile Corniche',
      zone: 'غرب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 21.4,
      numStops: 6,
      durationMinutes: 62,
      frequencyMinutes: 15,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-065',
      nameAr: 'المعصرة – رمسيس',
      nameEn: 'El-Masara – Ramses',
      fromAr: 'المعصرة',
      fromEn: 'El-Masara',
      toAr: 'رمسيس',
      toEn: 'Ramses',
      zone: 'جنوب القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 8.4,
      numStops: 11,
      durationMinutes: 33,
      frequencyMinutes: 5,
      fareEgp: 5,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-066',
      nameAr: 'السلام – القلعة',
      nameEn: 'El-Salam – The Citadel',
      fromAr: 'السلام',
      fromEn: 'El-Salam',
      toAr: 'القلعة',
      toEn: 'The Citadel',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 9.9,
      numStops: 19,
      durationMinutes: 32,
      frequencyMinutes: 8,
      fareEgp: 4,
      startTime: '05:30',
      endTime: '23:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-067',
      nameAr: 'النزهة – دار السلام',
      nameEn: 'El-Nozha – Dar El-Salam',
      fromAr: 'النزهة',
      fromEn: 'El-Nozha',
      toAr: 'دار السلام',
      toEn: 'Dar El-Salam',
      zone: 'شمال شرق / جنوب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 10.6,
      numStops: 6,
      durationMinutes: 35,
      frequencyMinutes: 7,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-068',
      nameAr: 'المقطم – مدينة نصر',
      nameEn: 'El-Mokattam – Nasr City',
      fromAr: 'المقطم',
      fromEn: 'El-Mokattam',
      toAr: 'مدينة نصر',
      toEn: 'Nasr City',
      zone: 'جنوب شرق / شرق القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 12.0,
      numStops: 12,
      durationMinutes: 38,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-069',
      nameAr: 'المعادي – المطرية',
      nameEn: 'Maadi – Matariya',
      fromAr: 'المعادي',
      fromEn: 'Maadi',
      toAr: 'المطرية',
      toEn: 'Matariya',
      zone: 'جنوب القاهرة / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 6.9,
      numStops: 20,
      durationMinutes: 19,
      frequencyMinutes: 12,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-070',
      nameAr: 'طره – روض الفرج',
      nameEn: 'Tura – Rod El-Farag',
      fromAr: 'طره',
      fromEn: 'Tura',
      toAr: 'روض الفرج',
      toEn: 'Rod El-Farag',
      zone: 'جنوب القاهرة / شمال القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 21.7,
      numStops: 12,
      durationMinutes: 56,
      frequencyMinutes: 7,
      fareEgp: 5,
      startTime: '05:30',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-071',
      nameAr: 'رمسيس – أكتوبر',
      nameEn: 'Ramses – October',
      fromAr: 'رمسيس',
      fromEn: 'Ramses',
      toAr: 'أكتوبر',
      toEn: 'October',
      zone: 'وسط القاهرة / غرب القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 15.6,
      numStops: 5,
      durationMinutes: 39,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-072',
      nameAr: 'الهرم – الزيتون',
      nameEn: 'El-Haram – Zeitoun',
      fromAr: 'الهرم',
      fromEn: 'El-Haram',
      toAr: 'الزيتون',
      toEn: 'Zeitoun',
      zone: 'جنوب غرب / شمال شرق',
      vehicleType: 'ميكروباص',
      lengthKm: 9.1,
      numStops: 13,
      durationMinutes: 33,
      frequencyMinutes: 8,
      fareEgp: 2,
      startTime: '05:00',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-073',
      nameAr: 'عابدين – الجمالية',
      nameEn: 'Abdin – El-Gamaliya',
      fromAr: 'عابدين',
      fromEn: 'Abdin',
      toAr: 'الجمالية',
      toEn: 'El-Gamaliya',
      zone: 'وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 4.7,
      numStops: 17,
      durationMinutes: 14,
      frequencyMinutes: 12,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-074',
      nameAr: 'شبرا – الهرم',
      nameEn: 'Shubra – El-Haram',
      fromAr: 'شبرا',
      fromEn: 'Shubra',
      toAr: 'الهرم',
      toEn: 'El-Haram',
      zone: 'شمال القاهرة / جنوب غرب',
      vehicleType: 'ميكروباص',
      lengthKm: 23.3,
      numStops: 12,
      durationMinutes: 65,
      frequencyMinutes: 15,
      fareEgp: 4,
      startTime: '05:00',
      endTime: '22:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
    PublicTransportRoute(
      id: 'MIC-075',
      nameAr: 'السلام – العتبة',
      nameEn: 'El-Salam – Ataba',
      fromAr: 'السلام',
      fromEn: 'El-Salam',
      toAr: 'العتبة',
      toEn: 'Ataba',
      zone: 'شرق القاهرة / وسط القاهرة',
      vehicleType: 'ميكروباص',
      lengthKm: 24.2,
      numStops: 9,
      durationMinutes: 87,
      frequencyMinutes: 15,
      fareEgp: 2,
      startTime: '05:30',
      endTime: '00:00',
      isCng: false,
      isAc: false,
      isAccessible: false,
    ),
  ];

  static const List<String> regionsAr = ['أكتوبر', 'إمبابة', 'الأزبكية', 'الأميرية', 'البساتين', 'التحرير', 'الجمالية', 'الخليفة', 'الدراسة', 'الدقي', 'الزمالك', 'الزيتون', 'السلام', 'السيدة زينب', 'العباسية', 'العتبة', 'القلعة', 'المرج', 'المطرية', 'المعادي', 'المعصرة', 'المقطم', 'المنيرة', 'المنيل', 'النزهة', 'الهرم', 'باب الشعرية', 'بدر', 'بشتيل', 'بولاق', 'بولاق الدكرور', 'جاردن سيتي', 'حلوان', 'دار السلام', 'رمسيس', 'روض الفرج', 'زين العابدين', 'شبرا', 'شبرا الخيمة', 'طره', 'عابدين', 'عباس العقاد', 'عين شمس', 'عين شمس الشرقية', 'فيصل', 'قصر النيل', 'كورنيش النيل', 'مدينة نصر', 'مصر الجديدة', 'مصر القديمة'];
  static const List<String> regionsEn = ['Abbas El-Akkad', 'Abbasiya', 'Abdin', 'Ain Shams', 'Ain Shams East', 'Amiriya', 'Ataba', 'Azbakeya', 'Bab El-Shaeria', 'Badr', 'Bashteel', 'Bulaq', 'Bulaq El-Dakrour', 'Dar El-Salam', 'Dokki', 'El-Basatin', 'El-Darasa', 'El-Gamaliya', 'El-Haram', 'El-Khalifa', 'El-Manial', 'El-Marg', 'El-Masara', 'El-Mokattam', 'El-Munira', 'El-Nozha', 'El-Salam', 'Embaba', 'Faisal', 'Garden City', 'Heliopolis', 'Helwan', 'Maadi', 'Matariya', 'Nasr City', 'Nile Corniche', 'October', 'Old Cairo', 'Qasr El-Nil', 'Ramses', 'Rod El-Farag', 'Sayeda Zeinab', 'Shubra', 'Shubra El-Kheima', 'Tahrir', 'The Citadel', 'Tura', 'Zamalek', 'Zein El-Abedin', 'Zeitoun'];

  static const Map<String, LatLng> regionCoords = {
    'مطار القاهرة': LatLng(30.1219, 31.3990),
    'Cairo Airport': LatLng(30.1219, 31.3990),
    'السلام': LatLng(30.1636, 31.4245),
    'El Salam': LatLng(30.1636, 31.4245),
    'رمسيس': LatLng(30.0633, 31.2467),
    'Ramses': LatLng(30.0633, 31.2467),
    'التحرير': LatLng(30.0444, 31.2357),
    'Tahrir': LatLng(30.0444, 31.2357),
    'الدقي': LatLng(30.0382, 31.2110),
    'Dokki': LatLng(30.0382, 31.2110),
    'المنيرة': LatLng(30.0270, 31.2350),
    'El Munira': LatLng(30.0270, 31.2350),
    'شبرا الخيمة': LatLng(30.1286, 31.2422),
    'Shubra El Kheima': LatLng(30.1286, 31.2422),
  };
}
